CommnClasses for Home Automation: msTimer Class Reference
msTimer Class Reference
#include <timerBase.h>
Public Member Functions
msTimer (int ms)
void timerStart (void)
int32_t read ()
bool run (bool flag)
void setOneShot (bool flag)
Private Attributes
uint32_t startTime =0
uint32_t elapsedTime =0
uint32_t duration
bool output =false
bool running =false
bool oneShot = false
bool triggered = false
Detailed Description
Definition at line 7 of file timerBase.h.
Constructor & Destructor Documentation
msTimer()
msTimer::msTimer (int ms)
Definition at line 11 of file timerBase.cpp.
{
     duration = ms;
 }
References duration.
Member Function Documentation
read()
int32_t msTimer::read ()
Definition at line 71 of file timerBase.cpp.
                       {
     struct timeval nowTV;
     gettimeofday(&nowTV, NULL);
     int nowTime = (nowTV.tv_sec * 1000) + (nowTV.tv_usec / 1000);
     return( nowTime - startTime );
 }
References startTime.
Referenced by run().
run()
bool msTimer::run (bool flag)
Definition at line 28 of file timerBase.cpp.
{
     if(runFlag == false) {
         running=false;
         output = false;
     } else {
         if( running == true) {
             int time = read();
             if( time > duration ) {
                 output=true;
             } else {
                 output=false;
                 triggered=false;
             }
         } else {
             // Running is false
             //
             timerStart();
             running = true;
             output=false;
             triggered=false;
         }
         if(output) {
             if( oneShot) {
                 if(triggered) {
                     output=false;
                 } else {
                     triggered = true;
                 }
             }
         }
     }
     cout << "Flag : " << output << endl;
     return output;
 }
References duration, oneShot, output, read(), running, timerStart(), and triggered.
Referenced by main().
setOneShot()
void msTimer::setOneShot (bool flag)
Definition at line 87 of file timerBase.cpp.
{
     oneShot = flag;
     triggered = false;
 }
References oneShot, and triggered.
Referenced by main().
timerStart()
void msTimer::timerStart (void)
Definition at line 21 of file timerBase.cpp.
{
     struct timeval startTV;
     gettimeofday(&startTV, NULL);
     startTime = (startTV.tv_sec * 1000) + (startTV.tv_usec / 1000);
 }
References startTime.
Referenced by run().
Field Documentation
duration
uint32_t msTimer::duration private
Definition at line 11 of file timerBase.h.
Referenced by msTimer(), and run().
elapsedTime
uint32_t msTimer::elapsedTime =0 private
Definition at line 10 of file timerBase.h.
oneShot
bool msTimer::oneShot = false private
Definition at line 15 of file timerBase.h.
Referenced by run(), and setOneShot().
output
bool msTimer::output =false private
Definition at line 13 of file timerBase.h.
Referenced by run().
running
bool msTimer::running =false private
Definition at line 14 of file timerBase.h.
Referenced by run().
startTime
uint32_t msTimer::startTime =0 private
Definition at line 9 of file timerBase.h.
Referenced by read(), and timerStart().
triggered
bool msTimer::triggered = false private
Definition at line 16 of file timerBase.h.
Referenced by run(), and setOneShot().
The documentation for this class was generated from the following files:
timerBase.h
timerBase.cpp