CommnClasses for Home Automation: tQueue Class Reference
tQueue Class Reference
#include <tQueue.h>
Public Member Functions
void push (std::string msg)
std::string pop ()
std::string get ()
int depth ()
void discard ()
Private Attributes
std::mutex mtx
std::queue< std::string > msgQueue
Detailed Description
Definition at line 10 of file tQueue.h.
Member Function Documentation
depth()
int tQueue::depth ()
Definition at line 60 of file tQueue.cpp.
                   {
     int s=0;
     mtx.lock();
     s=msgQueue.size();
     mtx.unlock();
     return s;
 }
Referenced by main().
discard()
void tQueue::discard ()
Definition at line 74 of file tQueue.cpp.
                      {
     mtx.lock();
     msgQueue.pop();
     mtx.unlock();
 }
get()
string tQueue::get ()
Definition at line 45 of file tQueue.cpp.
                    {
     string out;
     mtx.lock();
     out = msgQueue.front();
     mtx.unlock();
     return out;
 }
Referenced by main().
pop()
string tQueue::pop ()
Definition at line 29 of file tQueue.cpp.
                    {
     string out;
     mtx.lock();
     out = msgQueue.front();
     msgQueue.pop();
     mtx.unlock();
     return out;
 }
Referenced by main().
push()
void tQueue::push (std::string msg)
Definition at line 16 of file tQueue.cpp.
{
     mtx.lock();
     msgQueue.push(msg);
     mtx.unlock();
 }
Referenced by main().
Field Documentation
msgQueue
std::queue<std::string> tQueue::msgQueue private
Definition at line 13 of file tQueue.h.
mtx
std::mutex tQueue::mtx private
Definition at line 12 of file tQueue.h.
The documentation for this class was generated from the following files:
tQueue.h
tQueue.cpp