CommnClasses for Home Automation: edge Class Reference
edge Class Reference
#include <edge.h>
Public Member Functions
edge (TRANSITION t)
bool run (bool in)
Private Member Functions
bool positive (bool in)
bool negative (bool in)
Private Attributes
bool output =false
bool flag =false
TRANSITION whichEdge
Detailed Description
Definition at line 9 of file edge.h.
Constructor & Destructor Documentation
edge()
edge::edge (TRANSITION t)
Definition at line 34 of file edge.cpp.
{
     whichEdge = t;
 }
References whichEdge.
Member Function Documentation
negative()
bool edge::negative (bool in) private
Definition at line 70 of file edge.cpp.
{
     if( (in == false) && (flag == false) ) {
         flag = in;
         return false;
     }
     if( (in == false) && (flag == true) ) {
         flag = in;
         return true;
     }
     if( (in == true) && (flag == false )) {
         flag = in;
         return false;
     }
     if( (in == true) && (flag == true) ) {
         flag = in;
         return false;
     }
 }
References flag.
Referenced by run().
positive()
bool edge::positive (bool in) private
Definition at line 43 of file edge.cpp.
{
     if( (in == false) && (flag == false) ) {
         return false;
     }
     if( (in == false) && (flag == true) ) {
         flag = false;
         return false;
     }
     if( (in == true) && (flag == false )) {
         flag = true;
         return true;
     }
     if( (in == true) && (flag == true) ) {
         return false;
     }
 }
References flag.
Referenced by run().
run()
bool edge::run (bool in)
Definition at line 16 of file edge.cpp.
                       {
     switch( whichEdge) {
         case RISING:
             output=positive(in);
             break;
         case FALLING:
             output=negative(in);
             break;
     }
     return output;
 }
References FALLING, negative(), output, positive(), RISING, and whichEdge.
Referenced by main().
Field Documentation
flag
bool edge::flag =false private
Definition at line 12 of file edge.h.
Referenced by negative(), and positive().
output
bool edge::output =false private
Definition at line 11 of file edge.h.
Referenced by run().
whichEdge
TRANSITION edge::whichEdge private
Definition at line 14 of file edge.h.
Referenced by edge(), and run().
The documentation for this class was generated from the following files:
edge.h
edge.cpp