CommnClasses for Home Automation: plcSocket Class Reference
plcSocket Class Reference
#include <plcSocket.h>
Public Member Functions
plcSocket ()
plcSocket (string cfgFile)
void setServerSock (int)
string getValue (string shortName)
bool getBoolValue (string name)
void setValue (string shortName, string value)
void setBoolValue (string shortName, bool flag)
bool getStatus ()
void dump ()
void Ld (string symbol)
void Out (string symbol)
Public Member Functions inherited from plcBase
string getValue (string shortName)
string getOldValue (string)
void setValue (string shortName, string v)
bool setOldValue (string shortName, string v)
bool getBoolValue (string)
bool setBoolValue (string shortName, bool v)
bool getBoolOldValue (string)
bool setBoolOldValue (string shortName, bool v)
plcBase ()
void cacheDump ()
void setVerbose (bool)
bool Pop ()
void Push (bool v)
void display ()
void displayStack ()
void Ld (string symbol)
void Or ()
void And ()
void Invert ()
void Out (string symbol)
void End (int delay)
Private Member Functions
const void plcSetup (string cfg)
Private Attributes
string cfgFile = "/etc/mqtt/bridge.json"
string socketServer = "localhost"
int portNo = 9191
bool instanceFailed = true
json config
int serverSock
Additional Inherited Members
Protected Attributes inherited from plcBase
vector< bool > logicStack
bool verbose =false
Detailed Description
Definition at line 4 of file plcSocket.h.
Constructor & Destructor Documentation
plcSocket() [1/2]
plcSocket::plcSocket ()
Definition at line 135 of file plcSocket.cpp.
                      {
     plcSetup("/etc/mqtt/bridge.json");
 }
plcSocket() [2/2]
plcSocket::plcSocket (string cfgFile)
Definition at line 145 of file plcSocket.cpp.
{
     plcSetup(cfgFile);
 }
Member Function Documentation
dump()
void plcSocket::dump ()
Definition at line 196 of file plcSocket.cpp.
                      {
     cout << "Socket Server:" + socketServer << endl;
     cout << "Socket Fd    :" << serverSock << endl;
     cout << "Port         :" << portNo << endl;
 }
Referenced by main().
getBoolValue()
bool plcSocket::getBoolValue (string name)
Definition at line 67 of file plcSocket.cpp.
{
     string tmp = getValue(shortName);
     string res = rtrim(tmp);
     bool v = false ;
     if ( res == "ON" || res == "TRUE" ) {
         v = true;
     } else {
         v = false ;
     }
     return v;
 }
References rtrim().
getStatus()
bool plcSocket::getStatus ()
Definition at line 126 of file plcSocket.cpp.
{
     return instanceFailed;
 }
Referenced by main().
getValue()
string plcSocket::getValue (string shortName)
Definition at line 42 of file plcSocket.cpp.
{
     string res = "UNKNOWN";
     string tmp;
     char buffer[64];
     bzero(buffer, sizeof(buffer));
     string cmd = "GET " + shortName + "\r\n";
     if( serverSock > 0) {
         int len  = write(serverSock, (char *)cmd.c_str(), (int)cmd.length());
         errno = 0;
         len = read(serverSock, buffer, sizeof(buffer));
         if( len > 0) {
             tmp=buffer;
             res = rtrim(tmp);
         } else {
             perror( "plcSocket::getValue");
         }
     }
     return res;
 }
References rtrim().
Ld()
void plcSocket::Ld (string symbol)
Definition at line 206 of file plcSocket.cpp.
{
     if(verbose) {
         cout << "plcBase::Ld " << symbol ;
     }
     Push( getBoolValue(symbol));
     if(verbose) {
         cout << "   TOS: " << logicStack.back() << endl;
     }
 }
Referenced by main().
Out()
void plcSocket::Out (string symbol)
Definition at line 218 of file plcSocket.cpp.
{
     setBoolValue(symbol, Pop());
 }
plcSetup()
const void plcSocket::plcSetup (string cfg) private
Definition at line 82 of file plcSocket.cpp.
{
     plcBase::verbose = false;
     struct sockaddr_in si_other;
     socklen_t slen=sizeof(si_other);
     int sock;
     cout << "Config :" + cfgFile << endl;
     if(access(cfgFile.c_str(), R_OK) < 0) {
         cerr << "FATAL: Cannot access config file " + cfgFile << endl;
         instanceFailed = true;
     } else {
         int status=-1;
         ifstream cfgStream( cfgFile );
         config = json::parse(cfgStream);
         socketServer = config["socket"]["name"];
         string portNoString =  config["socket"]["port"] ;
         portNo = stoi( portNoString );
         sock = socket(AF_INET , SOCK_STREAM , 0);
         if ( sock == -1) {
             instanceFailed = true;
         } else {
             memset((char *) &si_other, 0, sizeof(si_other));
             si_other.sin_addr.s_addr = inet_addr( (char *)socketServer.c_str() );
             si_other.sin_family = AF_INET;
             si_other.sin_port = htons(portNo);
             if ( connect(sock , (struct sockaddr *)&si_other , sizeof(si_other)) < 0) {
                 cerr << "Connect failed" << endl;
                 instanceFailed = true;
             } else {
                 instanceFailed = false;
                 serverSock=sock;
             }
         }
     }
 }
References plcBase::verbose.
setBoolValue()
void plcSocket::setBoolValue (string shortName, bool flag)
Definition at line 189 of file plcSocket.cpp.
{
     string value = (flag) ? "ON" : "OFF";
     setValue(shortName, value);
 }
setServerSock()
void plcSocket::setServerSock (int fd)
Definition at line 202 of file plcSocket.cpp.
{
     serverSock = fd;
 }
setValue()
void plcSocket::setValue (string shortName, string value)
Definition at line 168 of file plcSocket.cpp.
{
     char buffer[64];
     string cmd = "SET " + shortName + " " + value + "\r" ;
     int len = write(serverSock, cmd.c_str(), cmd.length() );
     if( len < 0 ) {
         cerr << "plcSocket::setValue read: Returned an error" << endl;
         perror("WRITE");
     }
     fsync( serverSock );
     //
     //  This read could be used to verify that the write took place.
     //
     len = read(serverSock, buffer, sizeof(buffer));
     if( len < 0 ) {
         cerr << "plcSocket::setValue read: Returned an error" << endl;
         perror("READ");
     }
 }
Field Documentation
cfgFile
string plcSocket::cfgFile = "/etc/mqtt/bridge.json" private
Definition at line 6 of file plcSocket.h.
config
json plcSocket::config private
Definition at line 11 of file plcSocket.h.
instanceFailed
bool plcSocket::instanceFailed = true private
Definition at line 10 of file plcSocket.h.
portNo
int plcSocket::portNo = 9191 private
Definition at line 8 of file plcSocket.h.
serverSock
int plcSocket::serverSock private
Definition at line 12 of file plcSocket.h.
socketServer
string plcSocket::socketServer = "localhost" private
Definition at line 7 of file plcSocket.h.
The documentation for this class was generated from the following files:
plcSocket.h
plcSocket.cpp