CommnClasses for Home Automation: plcBase Class Reference
plcBase Class Reference
#include <plcBase.h>
Public Member Functions
string getValue (string shortName)
string getOldValue (string)
void setValue (string shortName, string v)
bool setOldValue (string shortName, string v)
bool getBoolValue (string)
bool setBoolValue (string shortName, bool v)
bool getBoolOldValue (string)
bool setBoolOldValue (string shortName, bool v)
plcBase ()
void cacheDump ()
void setVerbose (bool)
bool Pop ()
void Push (bool v)
void display ()
void displayStack ()
void Ld (string symbol)
void Or ()
void And ()
void Invert ()
void Out (string symbol)
void End (int delay)
Protected Attributes
vector< bool > logicStack
bool verbose =false
Private Attributes
int fd
map< string, string > ioPoint
bool cacheHit = true
Detailed Description
Definition at line 24 of file plcBase.h.
Constructor & Destructor Documentation
plcBase()
plcBase::plcBase ()
Definition at line 182 of file plcBase.cpp.
                  {
     cout << "PLC Base" << endl;
 }
Member Function Documentation
And()
void plcBase::And ()
Definition at line 218 of file plcBase.cpp.
                   {
     if(verbose) {
         cout << "plcBase::And " ;
     }
     bool a = Pop()  ;
     bool b = Pop()  ;
     bool v = a&b;
     logicStack.push_back(v);
     if(verbose) {
         cout << "          TOS: " << logicStack.back() << endl;
     }
 }
Referenced by main().
cacheDump()
void plcBase::cacheDump ()
display()
void plcBase::display ()
Definition at line 24 of file plcBase.cpp.
                       {
     bool flag = logicStack.back( );
     if( flag ) {
         cout << "\tON" << endl;
     } else {
         cout << "\tOFF" << endl;
     }
 }
displayStack()
void plcBase::displayStack ()
Definition at line 35 of file plcBase.cpp.
{
     for(size_t i = logicStack.size(); i--;) {
         cout << "\t" << logicStack[i] << endl;
     }
 }
End()
void plcBase::End (int delay)
Definition at line 275 of file plcBase.cpp.
{
     while ( ! logicStack.empty() ) {
         logicStack.pop_back();
     }
     //
     // Simple, but niave solution.
     //
     // First time through wait delay ms then get time
     // second time
     //
     usleep( delay * 1000);
 }
getBoolOldValue()
bool plcBase::getBoolOldValue (string)
Definition at line 156 of file plcBase.cpp.
{
     bool failFlag=true;
     return failFlag;
 }
getBoolValue()
bool plcBase::getBoolValue (string name)
Definition at line 114 of file plcBase.cpp.
{
     bool value=false;
     string v = getValue(name);
     if( v == "UNKNOWN") {
         v= false;
     }
     if( v == "UNDEFINED") {
         v= false;
     }
     if( v == "NODATA") {
         v= false;
     }
     value = (v=="ON") ? true : false ;
     return value;
 }
getOldValue()
string plcBase::getOldValue (string)
Definition at line 88 of file plcBase.cpp.
{
     string ov="";
     return ov;
 }
getValue()
string plcBase::getValue (string shortName)
Definition at line 53 of file plcBase.cpp.
{
 //    json rec = getRow(shortName);
 //    return(rec["msg"]);
     return("UNIMPLEMENTED");
 }
Invert()
void plcBase::Invert ()
Definition at line 250 of file plcBase.cpp.
                      {
     if(verbose) {
         cout << "plcBase::Not " ;
     }
     bool a = Pop()  ;
     bool v = !a;
     logicStack.push_back(v);
     if(verbose) {
         cout << "   TOS: " << logicStack.back() << endl;
     }
 }
Referenced by main().
Ld()
void plcBase::Ld (string symbol)
Definition at line 200 of file plcBase.cpp.
{
     try {
         cacheHit = true;
         if(verbose) {
             cout << "plcBase::Ld " << symbol ;
         }
         bool v=getBoolValue( symbol );
         logicStack.push_back( v );
         if(verbose) {
             cout << "   TOS: " << logicStack.back() << endl;
         }
     } catch(int e) {
         cerr << symbol + ":Undefined " << e << endl;
     }
 }
Or()
void plcBase::Or ()
Definition at line 234 of file plcBase.cpp.
                  {
     if(verbose) {
         cout << "plcBase::Or " ;
     }
     bool a = Pop()  ;
     bool b = Pop()  ;
     bool v = a|b;
     logicStack.push_back(v);
     if(verbose) {
         cout << "   TOS: " << logicStack.back() << endl;
     }
 }
Referenced by main().
Out()
void plcBase::Out (string symbol)
Definition at line 265 of file plcBase.cpp.
{
 // Overload
 }
Pop()
bool plcBase::Pop ()
Definition at line 189 of file plcBase.cpp.
                   {
     bool a = logicStack.back();
     logicStack.pop_back();
     return a;
 }
Push()
void plcBase::Push (bool v)
Definition at line 196 of file plcBase.cpp.
{
     logicStack.push_back( flag );
 }
setBoolOldValue()
bool plcBase::setBoolOldValue (string shortName, bool v)
Definition at line 170 of file plcBase.cpp.
{
     bool failFlag=true;
     return failFlag;
 }
setBoolValue()
bool plcBase::setBoolValue (string shortName, bool v)
Definition at line 143 of file plcBase.cpp.
{
     bool failFlag=true;
     return failFlag;
 }
setOldValue()
bool plcBase::setOldValue (string shortName, string v)
Definition at line 101 of file plcBase.cpp.
{
     bool failFlag=true;
     return failFlag;
 }
setValue()
void plcBase::setValue (string shortName, string v)
Definition at line 67 of file plcBase.cpp.
{
     /*
     json outMsg=getRow( shortName) ;
     outMsg["msgType"]  = "DATA";
     outMsg["cmd"]      = "SET";
     outMsg["shortName"]=shortName;
     outMsg["direction"]="OUT";
     outMsg["msg"]=v;
     string out = outMsg.dump();
     write(fd, out.c_str(), out.length());
     */
 }
setVerbose()
void plcBase::setVerbose (bool flag)
Definition at line 40 of file plcBase.cpp.
{
     verbose = flag;
     if(verbose) {
         cout << "Verbose" << endl;
     }
 }
Field Documentation
cacheHit
bool plcBase::cacheHit = true private
Definition at line 29 of file plcBase.h.
fd
int plcBase::fd private
Definition at line 27 of file plcBase.h.
ioPoint
map<string, string> plcBase::ioPoint private
Definition at line 28 of file plcBase.h.
logicStack
vector<bool> plcBase::logicStack protected
Definition at line 31 of file plcBase.h.
verbose
bool plcBase::verbose =false protected
Definition at line 32 of file plcBase.h.
Referenced by plcSocket::plcSetup().
The documentation for this class was generated from the following files:
plcBase.h
plcBase.cpp