CommnClasses for Home Automation: plcSocket.cpp File Reference
plcSocket.cpp File Reference
#include "plcBase.h"
#include "plcSocket.h"
#include <string.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#include <strings.h>
#include <fstream>
Typedefs
using json = nlohmann::json
Functions
string & ltrim (string &s, const char *t=" \t\n\r\f\v")
string & rtrim (string &s, const char *t=" \t\n\r\f\v")
string & trim (string &s, const char *t=" \t\n\r\f\v")
Typedef Documentation
json
using json = nlohmann::json
Definition at line 17 of file plcSocket.cpp.
Function Documentation
ltrim()
string& ltrim (string & s, const char * t = " \t\n\r\f\v") inline
Definition at line 21 of file plcSocket.cpp.
{
     s.erase(0, s.find_first_not_of(t));
     return s;
 }
Referenced by trim().
rtrim()
string& rtrim (string & s, const char * t = " \t\n\r\f\v") inline
Definition at line 26 of file plcSocket.cpp.
{
     s.erase(s.find_last_not_of(t) + 1);
     return s;
 }
Referenced by plcSocket::getBoolValue(), plcSocket::getValue(), and trim().
trim()
string& trim (string & s, const char * t = " \t\n\r\f\v") inline
Definition at line 31 of file plcSocket.cpp.
{
     return ltrim(rtrim(s, t), t);
 }