CommnClasses for Home Automation: tstEdge.cpp File Reference
tstEdge.cpp File Reference
#include "edge.h"
#include <iostream>
Functions
void outputLogic (bool i)
int main ()
Function Documentation
main()
int main ()
Definition at line 18 of file tstEdge.cpp.
            {
     bool in=false;
     bool out=false;
     edge *t = new edge(RISING);
     edge *t1 = new edge(FALLING);
     cout << "POSITIVE EDGE" << endl;
     out=t->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = true;
     out=t->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = false;
     out=t->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = true;
     out=t->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = true;
     out=t->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = false;
     out=t->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     cout << "NEGATIVE EDGE" << endl;
     in = false;
     out=t1->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = true;
     out=t1->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = true;
     out=t1->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = false;
     out=t1->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = false;
     out=t1->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
     in = true;
     out=t1->run( in ) ;
     cout << "In   : " << in  << endl;
     outputLogic(out) ;
     cout << "======" <<endl;
 }
References FALLING, outputLogic(), RISING, and edge::run().
outputLogic()
void outputLogic (bool i)
Definition at line 7 of file tstEdge.cpp.
{
     cout << "State:   ";
     if( i == true  ) {
         cout << "TRUE";
     } else {
         cout << "FALSE";
     }
     cout << endl;
 }
Referenced by main().