CommnClasses for Home Automation: tstIncCounter.cpp File Reference
tstIncCounter.cpp File Reference
#include "incCounter.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file tstIncCounter.cpp.
            {
     incCounter tst;
     cout << "init:" << tst.get() << endl;
     tst.increment();
     cout << "inc :" << tst.get() << endl;
     tst.decrement();
     cout << "dec :" << tst.get() << endl;
     tst.decrement();
     cout << "dec :" << tst.get() << endl;
 }
References incCounter::decrement(), incCounter::get(), and incCounter::increment().