CommnClasses for Home Automation: tstPlc.cpp File Reference
tstPlc.cpp File Reference
#include <plcBase.h>
#include <plcSocket.h>
#include "alarmBase.h"
#include <iostream>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 9 of file tstPlc.cpp.
            {
     plcSocket *plc = new plcSocket();
     bool failFlag = plc->getStatus();
     if(failFlag) {
         cerr << "FATAL ERROR: Instanciation of PLC socket failed." << endl;
         exit(1);
     }
     alarmBase *t = new alarmBase();
     cout << t->checkTime();
     t->setStartTime("05:30");
     plc->dump();
     plc->Ld("START");
     plc->Ld("MOTOR");
     plc->Or();
     plc->Ld("STOP");
     plc->Invert();
     plc->And();
 }
References plcBase::And(), alarmBase::checkTime(), plcSocket::dump(), plcSocket::getStatus(), plcBase::Invert(), plcSocket::Ld(), plcBase::Or(), and alarmBase::setStartTime().