CommnClasses for Home Automation: tstQ.cpp File Reference
tstQ.cpp File Reference
#include "tQueue.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 5 of file tstQ.cpp.
            {
     tQueue Q;
     string tst;
     cout << "Push ONE" << endl;
     Q.push("ONE");
     cout << Q.depth() << endl;
     cout << "Get ONE" << endl;
     tst = Q.get();
     cout << tst << endl;
     cout << Q.depth() << endl;
     cout << "Push TWO" << endl;
     Q.push("TWO");
     cout << Q.depth() << endl;
     cout << "Pop ONE" << endl;
     tst = Q.pop();
     cout << tst << endl;
     cout << Q.depth() << endl;
 }
References tQueue::depth(), tQueue::get(), tQueue::pop(), and tQueue::push().