CommnClasses for Home Automation: utils.h File Reference
utils.h File Reference
#include <vector>
#include <string>
#include <nlohmann/json.hpp>
Functions
std::string getFromJson (nlohmann::json j, std::vector< std::string > p, std::string defaultValue)
std::string addOffset (int hh, int mm, int off)
uid_t getUserIdByName (const char *name)
std::vector< std::string > split (const char *str, char c=' ')
std::string & ltrim (std::string &s, const char *t=" \t\n\r\f\v")
std::string & rtrim (std::string &s, const char *t=" \t\n\r\f\v")
std::string & trim (std::string &s, const char *t=" \t\n\r\f\v")
Function Documentation
addOffset()
std::string addOffset (int hh, int mm, int off)
Definition at line 49 of file utils.cpp.
{
     int ahh, amm;
     int minutes = (hh * 60) + mm;
     minutes += off;
     ahh = minutes / 60;
     amm = minutes % 60;
     string res = to_string(ahh) + ":" + to_string(amm);
     return res;
 }
getFromJson()
std::string getFromJson (nlohmann::json j, std::vector< std::string > p, std::string defaultValue)
Definition at line 13 of file utils.cpp.
{
     string v;
     string t;
     int len = p.size();
     try {
         switch(len) {
             case 0:
                 break;
             case 1:
                 v=j[ p[0]  ];
                 break;
             case 2:
                 {
                     string a = p[0];
                     string b = p[1];
                     v=j[a][b];
                 }
                 break;
             case 3:
                 v=j[p[0]] [p[1]] [p[2]];
                 break;
             default:
                 cerr << "getFromJson:FATAL Error, too many parameters, Max is 3" << endl;
                 exit(4);
                 break;
         }
     } catch (json::type_error &e) {
         v = defaultValue;
     }
     return v;
 }
getUserIdByName()
uid_t getUserIdByName (const char * name)
Definition at line 65 of file utils.cpp.
{
     struct passwd *pwd = getpwnam(name); /* don't free, see getpwnam() for details */
     if(pwd == NULL) {
         throw runtime_error(string("Failed to get userId from username : ") + name);
     }
     return pwd->pw_uid;
 }
ltrim()
std::string& ltrim (std::string & s, const char * t = " \t\n\r\f\v") inline
Definition at line 21 of file plcSocket.cpp.
{
     s.erase(0, s.find_first_not_of(t));
     return s;
 }
Referenced by trim().
rtrim()
std::string& rtrim (std::string & s, const char * t = " \t\n\r\f\v") inline
Definition at line 26 of file plcSocket.cpp.
{
     s.erase(s.find_last_not_of(t) + 1);
     return s;
 }
Referenced by plcSocket::getBoolValue(), plcSocket::getValue(), and trim().
split()
std::vector<std::string> split (const char * str, char c = ' ')
Definition at line 73 of file utils.cpp.
{
     vector<string> result;
     do {
         const char *begin = str;
         while(*str != c && *str)
             str++;
         result.push_back(string(begin, str));
     } while (0 != *str++);
     return result;
 }
trim()
std::string& trim (std::string & s, const char * t = " \t\n\r\f\v") inline
Definition at line 31 of file plcSocket.cpp.
{
     return ltrim(rtrim(s, t), t);
 }
References ltrim(), and rtrim().