DROP TABLE IF EXISTS io_point;
CREATE TABLE io_point ( name VARCHAR(32) NOT NULL UNIQUE, topic VARCHAR(128) DEFAULT 'NONE', direction VARCHAR(8) NOT NULL CHECK(direction = 'IN' 
OR direction = 'OUT' 
OR direction = 'DISABLED') DEFAULT 'DISABLED', state VARCHAR(8) NOT NULL DEFAULT 'UNKNOWN', on_state VARCHAR(4) DEFAULT 'ON', off_state VARCHAR(4) DEFAULT 'OFF' );
